CREATE DATABASE CAR_RENTAL;

CREATE TABLE CARS
(
    ID            INT IDENTITY (1,1) PRIMARY KEY,
    MAKER         NVARCHAR(100)  NOT NULL,
    MODEL         NVARCHAR(100)  NOT NULL,
    YEAR          INT            NOT NULL,
    COLOR         NVARCHAR(50)   NOT NULL,
    LICENSE_PLATE NVARCHAR(50)   NOT NULL,
    DAILY_PRICE   DECIMAL(10, 2) NOT NULL,
    IS_RENTED     BIT            NOT NULL DEFAULT 0
);

INSERT INTO CARS (MAKER, MODEL, YEAR, COLOR, LICENSE_PLATE, DAILY_PRICE, IS_RENTED)
VALUES ('VOLKSWAGEN', 'GOLF 5', 2008, 'SILVER', 'KH1234AB', 100.00, 0);

INSERT INTO CARS (MAKER, MODEL, YEAR, COLOR, LICENSE_PLATE, DAILY_PRICE, IS_RENTED)
VALUES ('BMW', 'X5', 2022, 'BLACK', 'CB5678CK', 90.00, 0);

INSERT INTO CARS (MAKER, MODEL, YEAR, COLOR, LICENSE_PLATE, DAILY_PRICE, IS_RENTED)
VALUES ('FORD', 'FOCUS', 2019, 'BLUE', 'CA9012EP', 40.00, 1);